excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://WendyHughes.github.io
title: Awesome
email: 
author: Wendy Hughes
description: My awesome new site
paginate: 3
google_analytics: 